-- Gerado por Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   em:        2022-05-24 15:38:27 BRT
--   site:      SQL Server 2012
--   tipo:      SQL Server 2012



CREATE TABLE CADASTRO_Hom 
    (
     REGISTRO_ID INTEGER , 
     MATRICULA VARCHAR (100) , 
     FONE VARCHAR (20) , 
     PIS INTEGER , 
     EMAIL VARCHAR (100) , 
     GRUPO VARCHAR (50) , 
     NUMERO_CRACHA VARCHAR (15) , 
     SENHA VARCHAR (20) , 
     CADASTRO_ID INTEGER NOT NULL IDENTITY NOT FOR REPLICATION 
    )
GO

ALTER TABLE CADASTRO_Hom ADD CONSTRAINT CADASTRO_PK PRIMARY KEY CLUSTERED (CADASTRO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CARGO_Hom 
    (
     CARGO_ID INTEGER NOT NULL , 
     NOME_CARGO VARCHAR (100) , 
     NOME_FUNCIONARIO VARCHAR (100) 
    )
GO

ALTER TABLE CARGO_Hom ADD CONSTRAINT CARGO_PK PRIMARY KEY CLUSTERED (CARGO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FUNCIONARIO_Hom 
    (
     FUNCIONARIO_ID INTEGER NOT NULL , 
     NOME VARCHAR (50) , 
     CPF VARCHAR (15) , 
     MATRICULA VARCHAR (20) , 
     HORARIO_TRABALHO VARCHAR (20) , 
     CARGO_CARGO_ID INTEGER , 
     SETOR VARCHAR (50) , 
     TORRE VARCHAR (10) , 
     CADASTRO_CADASTRO_ID INTEGER NOT NULL , 
     TELEFONE VARCHAR (20) 
    )
GO

ALTER TABLE FUNCIONARIO_Hom ADD CONSTRAINT FUNCIONARIO_PK PRIMARY KEY CLUSTERED (FUNCIONARIO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FUNCIONARIO_TERCEIRO_Hom 
    (
     FUNCIONARIOTERCEIRO_ID INTEGER NOT NULL , 
     NOME_FUNCIONARIO VARCHAR (100) , 
     CPF VARCHAR (15) , 
     SERVIÇO_PRESTADO VARCHAR (50) , 
     EMPRESA VARCHAR (50) NOT NULL , 
     OBSERVACAO VARCHAR (200) , 
     CADASTRO_CADASTRO_ID INTEGER , 
     TELEFONE_FUNCIONARIO VARCHAR (20) , 
     CNPJ VARCHAR (50) , 
     TELEFONE_EMPRESA VARCHAR (20) 
    )
GO

ALTER TABLE FUNCIONARIO_TERCEIRO_Hom ADD CONSTRAINT FUNCIONARIO_TERCEIRO_PK PRIMARY KEY CLUSTERED (FUNCIONARIOTERCEIRO_ID, EMPRESA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE REGISTRO_PONTO_Hom 
    (
     REGISTROPONTO_ID INTEGER NOT NULL , 
     NOME VARCHAR (100) , 
     MATRICULA VARCHAR (20) , 
     DATA_HORA_ENTRADA DATETIME , 
     DATA_HORA_SAIDA DATETIME , 
     OBSERVACAO VARCHAR (100) , 
     CADASTRO_CADASTRO_ID INTEGER 
    )
GO

ALTER TABLE REGISTRO_PONTO_Hom ADD CONSTRAINT REGISTRO_PONTO_PK PRIMARY KEY CLUSTERED (REGISTROPONTO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE FUNCIONARIO_Hom 
    ADD CONSTRAINT FUNCIONARIO_Hom_CADASTRO_Hom_FK FOREIGN KEY 
    ( 
     CADASTRO_CADASTRO_ID
    ) 
    REFERENCES CADASTRO_Hom 
    ( 
     CADASTRO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FUNCIONARIO_Hom 
    ADD CONSTRAINT FUNCIONARIO_Hom_CARGO_Hom_FK FOREIGN KEY 
    ( 
     CARGO_CARGO_ID
    ) 
    REFERENCES CARGO_Hom 
    ( 
     CARGO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FUNCIONARIO_TERCEIRO_Hom 
    ADD CONSTRAINT FUNCIONARIO_TERCEIRO_Hom_CADASTRO_Hom_FK FOREIGN KEY 
    ( 
     CADASTRO_CADASTRO_ID
    ) 
    REFERENCES CADASTRO_Hom 
    ( 
     CADASTRO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE REGISTRO_PONTO_Hom 
    ADD CONSTRAINT REGISTRO_PONTO_Hom_CADASTRO_Hom_FK FOREIGN KEY 
    ( 
     CADASTRO_CADASTRO_ID
    ) 
    REFERENCES CADASTRO_Hom 
    ( 
     CADASTRO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
